export const constRoute = {
  
  hash: "#",
  dashboard: "/",
  home: "/home",
  login: "/login",
  important: "/important",
  signup: "/signup",
  forgetPassword: "/forget-password",
  checkEmail: "/check-email",
  setNewPassword: "/set-new-password",
  resetPasswordSuccessfully: "/reset-password-successfully",
  verifyEmail: "/verify-email",
  selectFunction: "/select-function",
  finalSheet: "/final-sheet",
  profile: "/profile",
  setting: "/setting",
  loadBalance: "/load-balance-form",
  users: "/users",
  userBetForm: "/user-bet-form",
  recharges: "/recharges",
  soccer: "/soccer",
  tennis: "/tennis",
  cricket: "/cricket",
  betLocker: "/bet-locker",
  horseRace: "/horse-race",
  greyhound: "/greyhound",
  royalStarCasino: "/royal-star-casino",
  starCasino: "/star-casino",
  royalCasino: "/royal-casino",
  betFairGames: "/bet-fair-games",
  currentPosition: "/current-positions",
  allSports: "/all-sports",
  results: "/results",
  marketRules: "/market-rules",
  termsAndConditions: "/terms-and-conditions",
};
