

//// querry param keys ////

export const LOWER_PAGE_PARAM_KEY = "page"
export const LOWER_NUM_RECORDS_PARAM_KEY = "NumRecords"
export const LOWER_LIMIT_PARAM_KEY = "limit"


//// Initial Value Constant ////
export const INITIAL_NUM_RECORDS = 10
export const INITIAL_PAGE_NUMBER  = 1
export const INITIAL_QUERY_PARAM = `?${LOWER_PAGE_PARAM_KEY}=${INITIAL_PAGE_NUMBER}&${LOWER_NUM_RECORDS_PARAM_KEY}=${INITIAL_NUM_RECORDS}`




//// PROPS CONSTANTS ////
export const HASH_LINK = "#";
export const COLON  = ": "
export const LOWER_TARGET_BLANK = "_blank";
export const LOWER_SUBMIT = "submit";
export const COLOR_BLACK = "#000";
export const LOWER_COLOR_WHITE = "#fff";
export const LOWER_CENTER = "center";
export const LOWER_BODY_ONE = "body1";
export const LOWER_BASIC = "basic";
export const INITIAL_VALUES = { remember: true };
export const LOWER_OFF = "off";
export const LOWER_EMAIL = "email";
export const CAMEL_ON_BLUR = "onBlur";
export const LOWER_LABLE_BETWEEN_MIN_MAX =
  "${label} must be between ${min} and ${max}";
export const CAP_USER_NAME = "Username";
export const LOWER_USER_NAME = "username";
export const CAMEL_USER_ID = "userId";
export const UPPER_ID = "ID";
export const LOWER_DARK = "dark";
export const LOWER_LIGHT = "light";
export const LOWER_TRANSPARENT = "transparent";
export const LOWER_PASSWORD = "password";
export const CAP_REFERENCE = "Reference";
export const LOWER_REFERENCE = "reference";
export const CAP_NOTES = "Notes";
export const CAP_PASSWORD = "Password";
export const LOWER_TEXT = "text";
export const LOWER_HORIZONTAL = "horizontal";
export const LOWER_VERTICAL = "vertical";
export const LOWER_CHECKED = "checked";
export const CAMEL_USER_NAME = "userName";
export const LOWER_ROLE = "role";
export const CAP_SEARCH = "Search";
export const LOWER_LARGE = "large";
export const CAP_LARGE = "Large";
export const CAP_SMALL = "Small";
export const LOWER_SMALL = "small";
export const LOWER_FILLED = "filled";
export const LOWER_OUTLINED = "outlined";
export const CAP_CREDIT = "Credit";
export const LOWER_CREDIT = "credit";
export const CAP_CLIENT_PL = "Client P/L";
export const CAMEL_CLIENT_PL = "clientPL";
export const CAP_EXPOSURE = "Exposure";
export const LOWER_EXPOSURE = "exposure";
export const LOWER_ONE_O_BET_DOT_COM = "1obet.com"
export const CAP_EDIT = "Edit";
export const CAP_MAX_BET_SIZES = "Max Bet Sizes";
export const LOWER_EDIT = "edit";
export const CAP_UPDATE = "Update";
export const CAP_RECHARED_BY = "Recharged By";
export const CAP_RECHARES = "Recharges";
export const CAMEL_RECHARGED_BY = "rechargedBy";
export const CAMEL_CREATED_BY = "createdBy";
export const LOWER_AMOUNT = "amount";
export const CAP_AMOUNT = "Amount";
export const CAP_CREATED_BY = "Created By";
export const CAP_OPTIONS = "Options";
export const LOWER_OPTIONS = "options";
export const CAP_ACTION = "Action";
export const LOWER_ACTION = "action";
export const LOWER_KABBADI = "kabbadi"
export const LOWER_SNOOKER = "snooker"
export const CAMEL_ICE_HOCKEY = "iceHockey"
export const CAP_SHOW = "Show";
export const CAP_ENTRIES = "Entries";


 
//// TEXT CONSTANTS ////
export const CAP_KABBADI = "Kabbadi"
export const CAP_SNOOKER = "Snooker"
export const CAP_ICE_HOCKEY = "IceHockey"
export const CAP_SUBMIT = "Submit";
export const CAP_ADD_BTN_TITLE = "Add"
export const CAP_ABOUT = "About";
export const CAP_ABOUT_US = "About Us";
export const CAP_NAME = "Name";
export const CAP_SELF = "Self";
export const CAP_UNDERAGE = "Underage";
export const CAP_DISPUTE_RESOLUTION = "Dispute Resolution";
export const UPPER_AML = "AML";
export const LOWER_EXCLUSION = "exclusion";
export const LOWER_NONE = "none";
export const LOWER_BOLD = "bold";
export const CAMEL_IS_ACTIVE = "isActive";
export const UPPER_OUR_POLICIES = "OUR POLICIES";
export const CAP_LOGO = "Logo";
export const LOWER_NOT_VALID = "is not a valid";
export const LOWER_CHECK_BOX = "check box";
export const LOWER_IS_REQUIRED = "is required";
export const LOWER_LABLE_REQUIRED = "${label} " + LOWER_IS_REQUIRED;
export const LOWER_LABEL_NOT_VALID = "${label} " + LOWER_NOT_VALID;
export const CAP_EMAIL = "Email";
export const LOWER_NUMBER = "number";
export const LOWER_TEXT_AREA = "textarea";
export const CAP_LOGIN = "Login";
export const UPPER_O_BET = "OBET";
export const LOWER_ERROR = "error";
export const LOWER_TOKEN = "token";
export const CAP_CREATE = "Create";
export const CAP_MAX = "Max";
export const CAP_FINAL_SHEET = "Final Sheet";
export const CAP_JUSTIFY_ICON = "Justify Icon";
export const CAP_HIDE_ZERO_AMOUNTS = "Hide Zero Amounts";
export const CAP_MIN = "Min";
export const CAP_NEW = "New";
export const CAP_TOTAL = "Total";
export const CAP_USER = "User";
export const CAP_CREATE_NEW = CAP_CREATE + " " + CAP_NEW;
export const CAP_SELECT = "Select";
export const CAMEL_SELECT_USER = "selectUser";
export const SEN_SELECT_USER = "Select user";
export const CAP_SHARE = "Share";
export const LOWER_SHARE = "share";
export const LOWER_BETTOR = "bettor";
export const CAMEL_SUPER_MASTER = "superMaster";
export const CAP_TYPE = "Type";
export const LOWER_TYPE = "type";
export const CAP_PHONE = "Phone";
export const CAP_USERDOMAIN = "UserDomain";
export const CAMEL_USERDOMAIN = "userDomain";
export const CAP_BOOKMAKER = "BookMaker";
export const CAMEL_BOOKMAKER = "bookMaker";
export const LOWER_PHONE = "phone";
export const LOWER_NOTES = "notes";
export const CAP_DOWNLINE = "Downline"
export const CAMEL_DOWN_LINE_SHARE = "downLineShare"
export const CAP_DOWN_LINE_SHARE = CAP_DOWNLINE + CAP_SHARE;
export const CAP_BALANCE = "Balance";
export const LOWER_BALANCE = "balance";
export const CAP_AVAILABLE_BALANCE = "Available Balance";
export const CAMEL_AVAILABLE_BALANCE = "availableBalance";
export const CAP_LOAD_BALANCE = "Load Balance";
export const LOWER_MUST_BE_GREATER_THAN = "must be greater than";
export const LOWER_MUST_BE_LESS_THAN = "must be less than";
export const LOWER_MUST_BE_BETWEEN = "must be between";
export const CAMEL_USER_TYPE = "userType";
export const CAP_ACCOUNT = "Accounts";
export const CAP_ACCOUNT_AND_BONUSES = "Accounts & Bonuses";
export const CAP_COMMISSION = "Commission";
export const LOWER_COMMISSION = "commission";
export const CAP_COMPANY = "Company";
export const CAP_SUPER_ADMIN = "Super Admin";
export const CAP_ADMIN = "Admin";
export const CAP_SUPER_MASTER = "Super Master";
export const CAP_MASTER = "Master";
export const CAP_BETTOR = "Bettor";
export const CAP_PRIVACY = "Privacy";
export const CAP_POLICY = "Policy";
export const CAP_RULES_AND_REGULATIONS = "Rules and Regulations";
export const UPPER_KYC = "KYC";
export const UPPER_RNG = "RNG";
export const CAP_FAIRNESS_AND = "Fairness &";
export const CAP_RESPONSIBLE_GAMING = "Responsible Gaming";
export const CAP_FANCY = "Fancy";
export const LOWER_FANCY = "fancy";
export const CAP_LIGHT_THEME = "Light Theme";
export const CAP_DARK_THEME = "Dark Theme";
export const CAP_GREY_THEME = "Grey Theme";
export const LOWER_LIGHT_HYPEN_THEME = "light-theme";
export const LOWER_DARK_HYPEN_THEME = "dark-theme";
export const LOWER_GREY_HYPEN_THEME = "grey-theme";
export const LOWER_THEME = "theme";
export const NUM_STR_0 = "0";
export const NUM_STR_1 = "1";
export const NUM_STR_2 = "2";
export const NUM_STR_3 = "3";
export const NUM_STR_4 = "4";
export const NUM_STR_5 = "5";
export const NUM_STR_0_ROLE = "0"
export const NUM_STR_1_ROLE = "1"
export const NUM_STR_2_ROLE = "2"
export const NUM_STR_3_ROLE = "3"
export const NUM_STR_4_ROLE = "4"
export const NUM_STR_5_ROLE = "5"
export const CAP_HELLO = "Hello";
export const DASH = "-";
export const DOUBLE_DASH = "--";
export const CAP_CAN_SETTLE_PL = "Can Settle PL";
export const CAMEL_CAN_SETTLE_PL = "canSettlePL";
export const UPPER_T_DASH_PIN = "T-PIN";
export const CAMEL_T_PIN = "tPin";
export const CAP_NEW_USER = "New User";
export const CAP_LEDGER = "Ledger";
export const CAP_BETTING_ALLOWED = "Betting Allowed";
export const CAMEL_BETTING_ALLOWED = "bettingAllowed";
export const CAP_ACCOUNT_LEDGER = "Account Ledger";
export const CAP_CASH_SLASH_CREDIT = "Cash / Credit";
export const CAP_ACTIVE = "Active";
export const CAP_IN_ACTIVE = "In Active";
export const CAMEL_ISACTIVE = "isActive";
export const CAP_SETTLE_ACCOUNT = "Settle Account";
export const CAP_ALL_RECHARGES = "All Recharges";
export const CAP_DASHBOARD = "Dashboard";
export const CAP_USERS = "Users";
export const CAP_CURRENT_POSITIONS = "Current Positions";
export const CAP_STAR_CASINO = "Star Casino";
export const CAP_CASINO = "Casino";
export const LOWER_CASINO = "casino";
export const CAP_CURRENCY = "Currency";
export const LOWER_CURRENCY = "currency";
export const CAP_BET_FAIR_GAMES = "Bet Fair Games";
export const CAP_SOCCER = "Soccer";
export const LOWER_SOCCER = "soccer";
export const CAP_TENNIS = "Tennis";
export const LOWER_TENNIS = "tennis";
export const CAP_CRICKET = "Cricket";
export const CAP_CUP_WINNER = "Cup Winner";
export const CAP_EVEN_DASH_ODD = "Even / Odd";
export const CAP_BETERFAIR_GAMES = "Betfair Games"
export const LOWER_CRICKET = "cricket";
export const CAP_AUSTRALIA = "Australia";
export const CAP_BRITAIN = "Britain";
export const CAP_NEW_ZEALAND = "New Zealand";
export const CAP_ALLOWED_MARKET_TYPES ="Allowed Market Types";
export const CAP_RACES = "Races";
export const CAP_FIGURE = "Figure";
export const CAP_MATCH_ODDS = "Match Odds";
export const CAP_SUPER_NOVA = "Super Nowa";
export const CAP_TOSS = "Toss";
export const CAP_BET_LOCK = "Bet Lock";
export const LOWER_RACES = "races";
export const CAP_HORSE_RACE = "Horse Race";
export const CAP_GREYHOUND = "Greyhound";
export const LOWER_GREYHOUND = "greyhound";
export const CAP_ROYALSTAR_CASINO = "RoyalStar Casino";
export const CAP_ALL_SPORTS = "All Sports";
export const CAP_RESULTS = "Results";
export const MARKET_RULES = "Market Rules";
export const CAP_TERMS_AND_CONDITIONS = "Terms and Conditions";
export const CAP_CASH = "Cash";
export const CAP_DESCRIPTION = "Description";
export const LOWER_DESCRIPTION = "description";
export const LOWER_PAYMENT = "payment";
export const CASH_PAYMENT = `${CAP_CASH} ${LOWER_PAYMENT}`;
export const CAP_RS = `Rs.`;
export const CAP_DEPOSITE = `Deposite`;
export const LOWER_DEPOSITE = `deposite`;
export const CAP_WITHDRAW = `Withdrawn`;
export const LOWER_WITHDRAW = `withdrawn`;
export const CAP_SUSPENDED = `Suspended`;
export const CAP_START_DATE= `Start Date`;
export const CAP_END_DATE = `End Date`;
export const CAP_DEPOSITE_CASH = `${CAP_DEPOSITE} ${CAP_CASH}`;
export const CAP_WITHDRAW_CASH = `${CAP_WITHDRAW} ${CAP_CASH}`;
export const LABEL_COL={xxl: 10, lg: 10, md: 10, xs: 10 };
export const WRAPPER_COL={ xxl: 14, lg: 14, md: 12, xs: 12 };
export const NUM_12 = 12;
export const NUM_24 = 24;
export const NUM_4 = 4;
export const NUM_2 = 2;
export const NUM_8 = 8;
export const NUM_6 = 6;
export const NUM_250000 = 250000;
export const NUM_50000 = 50000;
export const NUM_200000 = 200000;
export const NUM_2000000 = 2000000;
export const NUM_5000000 = 5000000;
export const SEN_ARE_YOU_SURE_YOU_WANT_TO =  "Are you sure you want to" 
export const LOWER_IS_ALREADY_EXIST = "is already exist"
export const SEN_THIS_ACTION_CONNOT_BE_UNDONE = "This action cannot be undone."


//// Title Constants ////**
export const CAP_ACCEPT_BTN_TITLE = "Accept"
export const CAP_CONFIRM_BTN_TITLE = "Confirm"
export const CAP_DECLINE_BTN_TITLE = "Decline"
export const CAP_CANCEL_BTN_TITLE = "Cancel"